name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt" # Options: adopt, zulu, etc.
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs dependencies from requirements.txt

      - name: Set environment variable
        run: |
          echo "DB_CONNECTION_STRING=sqlite://" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          pytest --cov=app tests/

      - name: Download and install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d sonar-scanner
          echo "SONAR_SCANNER_HOME=$(pwd)/sonar-scanner/sonar-scanner-4.6.2.2472-linux" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_ENV

      - name: Upload coverage to SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=ManassehV2_aptarapi \
          -Dsonar.organization=manassehv2 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.python.coverage.reportPaths=coverage.xml
